[profile.default]
src = 'src'
solc = '0.8.24'
evm_version = 'paris'
out = 'out'
libs = ['lib']
test = 'test'
cache_path = 'cache_forge'
remappings = [
    '@chainlink/contracts-ccip/=lib/ccip/contracts/',
    '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
    '@chainlink/local/src/=src/',
]

[dependencies]
"smartcontractkit-ccip" = { version = "2.17.0-ccip1.5.12"}
"smartcontractkit-chainlink-brownie-contracts" = {version = "1.3.0"}